# Generated by Django 5.0.1 on 2024-01-28 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_name', models.CharField(max_length=100)),
                ('sentence_ender', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='animituser',
            name='animal_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='animit_users', to='animit.animal'),
        ),
    ]
